// Curated substance-law snapshot, mid-2026. Country → [status, note].
// Unlisted countries take the layer default. Laws change fast: this is a
// travel-planning summary, not legal advice — verify locally.
const SUBSTANCES = {
  updated: "2026-09",

  cannabis: {
    default: "illegal",
    CA: ["legal", "Recreational legal nationwide since 2018"],
    UY: ["legal", "First country to legalise (2013): pharmacies, clubs, home grow"],
    DE: ["legal", "Legal since April 2024: 25 g possession, home grow, cannabis clubs"],
    MT: ["legal", "Legal since 2021: home grow + non-profit associations"],
    LU: ["legal", "Home grow (4 plants) and private use legal since 2023"],
    ZA: ["legal", "Private use and cultivation legal; Cannabis for Private Purposes Act 2024"],
    GE: ["legal", "Consumption legal since 2018; sale and cultivation still illegal"],
    US: ["mixed", "Legal in ~24 states + DC, medical in most others; still federally illegal"],
    AU: ["mixed", "Medical nationwide; ACT allows personal possession and home grow"],
    TH: ["medical", "Delisted 2022, re-restricted 2025: prescription needed for use"],
    NL: ["decrim", "Tolerated: coffeeshops sell ≤5 g; production still illegal"],
    ES: ["decrim", "Private use and clubs tolerated; public use fined"],
    PT: ["decrim", "All personal drug use decriminalised since 2001"],
    CZ: ["decrim", "Small amounts an administrative offence; home grow (3 plants) from 2026"],
    CH: ["decrim", "≤10 g not prosecuted; regulated pilot sales in several cities"],
    AT: ["decrim", "Small amounts: therapy instead of prosecution"],
    BE: ["decrim", "≤3 g tolerated for adults in private"],
    IT: ["decrim", "Personal use: administrative sanctions only"],
    HR: ["decrim", "Personal possession a misdemeanour"],
    SI: ["decrim", "Personal possession a minor offence"],
    EE: ["decrim", "Small amounts an administrative offence"],
    CO: ["decrim", "Personal dose decriminalised; home grow up to 20 plants"],
    AR: ["decrim", "Court rulings protect private use; medical home grow registry"],
    CL: ["decrim", "Private use not prosecuted; medical programme"],
    PE: ["decrim", "≤8 g possession legal for personal use"],
    EC: ["decrim", "Possession thresholds decriminalised"],
    CR: ["decrim", "Possession not penalised; medical/hemp law 2022"],
    PY: ["decrim", "≤10 g decriminalised"],
    BR: ["decrim", "Supreme Court 2024: ≤40 g possession not a crime"],
    MX: ["decrim", "Supreme Court struck down the personal-use ban; regulation stalled"],
    JM: ["decrim", "≤2 oz decriminalised; sacramental and medical use legal"],
    TT: ["decrim", "≤30 g decriminalised since 2019"],
    AG: ["decrim", "≤15 g decriminalised since 2018"],
    BZ: ["decrim", "≤10 g decriminalised"],
    BM: ["decrim", "≤7 g decriminalised"],
    IL: ["decrim", "First offences fined; large medical programme"],
    LB: ["medical", "Medical and industrial cultivation legalised 2020"],
    MA: ["medical", "Medical and industrial cannabis legal since 2021"],
    UA: ["medical", "Medical cannabis legalised December 2023"],
    GB: ["medical", "Prescription-only since 2018; recreational illegal (Class B)"],
    IE: ["medical", "Limited medical access programme"],
    NZ: ["medical", "Medical scheme; 2020 legalisation referendum narrowly failed"],
    DK: ["medical", "Medical pilot; recreational illegal"],
    FI: ["medical", "Medical on special permit only"],
    PL: ["medical", "Medical prescriptions widely available"],
    GR: ["medical", "Medical legal since 2017"],
    CY: ["medical", "Medical legal"],
    RO: ["medical", "Medical products permitted"],
    RW: ["medical", "Medical cultivation for export"],
    ZW: ["medical", "Medical and industrial licences"],
    ZM: ["medical", "Medical and export cultivation"],
    MW: ["medical", "Medical and industrial licences since 2020"],
    LS: ["medical", "First African country to license medical cultivation"],
    BB: ["medical", "Medical and sacramental use legal"],
    VC: ["medical", "Medical cannabis industry"],
    IN: ["mixed", "Cannabis illegal, but bhang (edible) legal in several states"],
    FR: ["illegal", "Fixed €200 fine for use; medical trial only"],
    SE: ["illegal", "Use itself is a crime"],
    NO: ["illegal", "Illegal; harm-reduction policy"],
    HU: ["illegal", "Illegal"],
    RU: ["illegal", "Illegal; prison for possession above small amounts"],
    BY: ["illegal", "Illegal, harsh sentences"],
    TR: ["illegal", "Illegal; medical CBD only"],
    JP: ["illegal", "Illegal; use criminalised 2024, medical CBD products allowed"],
    KR: ["illegal", "Illegal, also for citizens abroad"],
    NP: ["illegal", "Illegal since 1973; relegalisation bill pending"],
    EG: ["severe", "Illegal; prison for possession"],
    CN: ["severe", "Illegal; death penalty for trafficking"],
    SG: ["severe", "Death penalty for trafficking; caning for possession"],
    MY: ["severe", "Death penalty possible for trafficking"],
    ID: ["severe", "Death penalty for trafficking; prison for possession"],
    PH: ["severe", "Harsh enforcement; medical bill pending"],
    VN: ["severe", "Death penalty for trafficking"],
    SA: ["severe", "Death penalty possible; flogging and prison"],
    AE: ["severe", "Prison; trace amounts prosecuted"],
    IR: ["severe", "Death penalty for trafficking"],
    QA: ["severe", "Prison and deportation"],
    KW: ["severe", "Prison; death penalty for trafficking"],
    BN: ["severe", "Death penalty for trafficking"],
    TN: ["severe", "Mandatory prison for use"],
  },

  alcohol: {
    default: "legal",
    SA: ["banned", "Banned; a single store for non-Muslim diplomats opened 2025"],
    IR: ["banned", "Banned for Muslims; small non-Muslim minorities exempt"],
    AF: ["banned", "Total ban"],
    LY: ["banned", "Total ban"],
    KW: ["banned", "Total ban"],
    YE: ["banned", "Banned (some Aden hotels historically excepted)"],
    SO: ["banned", "Banned"],
    MR: ["banned", "Banned for Muslims; licensed hotels only"],
    BN: ["banned", "Sale banned; non-Muslims may import a small allowance"],
    SD: ["restricted", "Ban lifted for non-Muslims in 2020"],
    IQ: ["restricted", "2023 import/sale ban, patchily enforced; Kurdistan sells freely"],
    PK: ["restricted", "Non-Muslims only, with permit"],
    BD: ["restricted", "Permit required; licensed bars and hotels"],
    MV: ["restricted", "Resort islands only; dry everywhere else"],
    QA: ["restricted", "Licensed hotels and permit holders only"],
    AE: ["restricted", "Licensed venues; Sharjah is dry"],
    OM: ["restricted", "Licensed venues and permit holders"],
    IN: ["restricted", "Dry states: Gujarat, Bihar, Mizoram, Nagaland, Lakshadweep"],
    MY: ["restricted", "Non-Muslims only; dry in Kelantan/Terengganu"],
    ID: ["restricted", "Aceh dry; provincial limits, minimarket ban"],
    NG: ["restricted", "Banned in several Sharia-law northern states"],
    TM: ["restricted", "State sales only, heavy limits"],
    DZ: ["restricted", "Legal but sales tightly limited"],
    EG: ["restricted", "Licensed venues; sales curbed during Ramadan"],
    JO: ["legal", "Licensed shops and bars"],
    US: ["legal", "Legal; some dry counties remain"],
  },

  tobacco: {
    default: "legal",
    BT: ["restricted", "Sales ban (2010–2021) lifted; heavy taxes, public-smoking bans"],
    TM: ["restricted", "Sales tightly restricted to state outlets"],
    GB: ["legal", "Generational sales ban legislated for anyone born after 2008"],
    AU: ["restricted", "Nicotine vapes prescription/pharmacy only since 2024"],
    JP: ["restricted", "Nicotine vapes not sold; heated tobacco huge"],
    SG: ["banned", "Nicotine vapes banned; fines and, since 2025, jail for some offences"],
    TH: ["banned", "Vapes banned; tourists fined"],
    IN: ["banned", "E-cigarettes banned since 2019"],
    BR: ["banned", "Vapes banned (ANVISA)"],
    MX: ["banned", "Vape sales banned; constitutional ban 2025"],
    AR: ["banned", "Vapes banned"],
    UY: ["banned", "Vapes banned"],
    VE: ["banned", "Vapes banned"],
    PA: ["banned", "Vapes banned"],
    TR: ["banned", "Vape imports banned"],
    IR: ["banned", "Vapes banned"],
    QA: ["banned", "Vapes banned"],
    OM: ["banned", "Vapes banned"],
    KW: ["banned", "Vapes banned"],
    KH: ["banned", "Vapes banned"],
    LA: ["banned", "Vapes banned"],
    VN: ["banned", "Vapes banned from 2025"],
    TW: ["banned", "Vapes banned since 2023"],
    HK: ["banned", "Vape sale and import banned since 2022"],
    MO: ["banned", "Vapes banned"],
    TL: ["banned", "Vapes banned"],
    SC: ["banned", "Vapes banned"],
    MU: ["banned", "Vapes banned"],
    KP: ["banned", "Vapes banned"],
    NP: ["banned", "Vapes banned 2025"],
  },

  psychedelics: {
    default: "illegal",
    JM: ["legal", "Psilocybin mushrooms unregulated; retreat industry"],
    BS: ["legal", "Psilocybin mushrooms legal"],
    NP: ["legal", "Psilocybin mushrooms unregulated"],
    BR: ["legal", "Mushrooms not scheduled; ayahuasca legal for religious use"],
    WS: ["legal", "Psilocybin mushrooms legal"],
    NL: ["legal", "Psilocybin truffles sold legally; dried mushrooms banned since 2008"],
    PT: ["decrim", "All personal drug use decriminalised"],
    CZ: ["decrim", "Small amounts an administrative offence"],
    ES: ["decrim", "Private use not criminal"],
    AT: ["decrim", "Grow kits legal; use decriminalised (therapy route)"],
    IT: ["decrim", "Personal use: administrative sanctions"],
    MX: ["decrim", "Indigenous ceremonial use exempt; otherwise illegal"],
    PE: ["decrim", "Ayahuasca and San Pedro legal (cultural heritage); mushrooms illegal"],
    CO: ["decrim", "Personal dose protected; yagé ceremonies legal"],
    EC: ["decrim", "Personal thresholds decriminalised"],
    CR: ["decrim", "Ayahuasca retreats operate openly; mushrooms unregulated"],
    AU: ["medical", "Psilocybin and MDMA prescribable by authorised psychiatrists since July 2023"],
    CA: ["medical", "Special Access Program for psilocybin therapy"],
    CH: ["medical", "Case-by-case medical exemptions for psilocybin/LSD/MDMA"],
    NZ: ["medical", "First psilocybin prescribing authorised 2025"],
    IL: ["medical", "Compassionate-use MDMA and psilocybin trials"],
    US: ["mixed", "Oregon and Colorado regulate psilocybin; federally Schedule I"],
    GB: ["illegal", "Class A; magic mushrooms banned 2005"],
    DE: ["illegal", "Illegal; grow kits sold in grey zone"],
    JP: ["illegal", "Banned since 2002"],
    KR: ["illegal", "Illegal"],
    SG: ["severe", "Class A; caning and long sentences"],
    ID: ["severe", "Illegal; harsh sentences"],
    MY: ["severe", "Illegal; harsh sentences"],
    TH: ["illegal", "Category 5 narcotic; mushroom-shake bars are illegal"],
    SA: ["severe", "Illegal; harsh penalties"],
    AE: ["severe", "Illegal; harsh penalties"],
  },

  decrim: {
    default: "no",
    PT: ["yes", "All drugs: possession for personal use an administrative matter since 2001"],
    CZ: ["yes", "Small amounts of any drug: administrative offence"],
    UY: ["yes", "Personal possession never criminalised"],
    CO: ["yes", "Personal dose protected by the Constitutional Court"],
    MX: ["yes", "Small amounts of all drugs decriminalised since 2009"],
    AR: ["yes", "Supreme Court: private use not punishable"],
    CR: ["yes", "Possession for personal use not penalised"],
    EC: ["yes", "Threshold table decriminalises personal amounts"],
    PE: ["yes", "Personal possession below thresholds is legal"],
    CL: ["yes", "Private personal use not prosecuted"],
    ES: ["yes", "Private consumption not a crime (public use fined)"],
    IT: ["yes", "Personal use: administrative sanctions"],
    HR: ["yes", "Personal possession a misdemeanour"],
    SI: ["yes", "Personal possession a minor offence"],
    EE: ["yes", "Personal possession an administrative offence"],
    PY: ["yes", "Small amounts decriminalised"],
    NL: ["yes", "De facto: personal possession not prosecuted (tolerance policy)"],
    DE: ["partial", "Cannabis legal; other drugs criminal"],
    LU: ["partial", "Cannabis only"],
    MT: ["partial", "Cannabis only"],
    JM: ["partial", "Cannabis only"],
    GE: ["partial", "Cannabis use only"],
    BE: ["partial", "Cannabis tolerated only"],
    AT: ["partial", "Therapy-instead-of-punishment for small amounts"],
    IL: ["partial", "Cannabis first offences only"],
    BR: ["partial", "Cannabis possession only (2024 ruling)"],
    TT: ["partial", "Cannabis only"],
    BZ: ["partial", "Cannabis only"],
    AG: ["partial", "Cannabis only"],
    CA: ["partial", "Cannabis legal; BC decriminalisation pilot curtailed 2024"],
    AU: ["partial", "ACT decriminalised small amounts of all drugs (2023); elsewhere cannabis-only reforms"],
    US: ["partial", "Oregon repealed all-drug decriminalisation in 2024; cannabis state-by-state"],
  },
};
